Modules/Asset/Routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => 'auth'], function () {

    // Admin routes
    Route::group(
        ['prefix' => 'admin', 'as' => 'admin.'],
        function () {
            Route::prefix('assets')->group(function () {
                Route::get('assets/lend/{id}', ['uses' => 'AssetController@lend'])->name('assets.lend');
                Route::post('assets/lend-store/{id}', ['uses' => 'AssetController@lendSubmit'])->name('assets.lend-store');

                Route::resource('assets', 'AssetController');

                Route::get('/asset/{asset}/history/return/{history}', ['uses' => 'AssetHistoryController@returnAsset'])->name('assets.return');
                Route::resource('/asset/{asset}/history', 'AssetHistoryController')->names([
                    'create' => 'history.create',
                    'store' => 'history.store',
                    'edit' => 'history.edit',
                    'update' => 'history.update',
                    'destroy' => 'history.destroy',
                ]);

                Route::post('asset-type/store', ['as' => 'asset-type.store', 'uses' => 'AssetTypeController@store']);
                Route::get('asset-type/create', ['as' => 'asset-type.create', 'uses' => 'AssetTypeController@create']);
                Route::delete('asset-type/destroy/{id}', ['as' => 'asset-type.destroy', 'uses' => 'AssetTypeController@destroy']);

            });

            Route::group(
                ['prefix' => 'settings'],
                function () {

                }
            );
        }
    );
});

Modules/Asset/Entities/Asset.php
<?php

namespace Modules\Asset\Entities;

use Illuminate\Database\Eloquent\Model;
use Modules\Asset\Observers\AssetObserver;

class Asset extends Model
{
    //region Properties

    protected $table = 'assets';
    protected $appends = ['image_url'];

    protected $hidden = [
        'created_at',
        'updated_at',
        'company_id',
        'location_id'
    ];

    protected $guarded = [
        'id',
        'created_at',
        'updated_at',
        'company_id'
    ];


    protected $dates = [
        'created_at',
        'updated_at'
    ];

    //endregion

    //region Boot

    public static function boot()
    {
        parent::boot();
        static::observe(AssetObserver::class);
    }

    //endregion


    public function history()
    {
        return $this->hasMany(AssetHistory::class);
    }


    public function asset_type()
    {
        return $this->belongsTo(AssetType::class, 'asset_type_id', 'id');
    }

    //endregion

    public function getImageUrlAttribute()
    {
        return ($this->image) ? asset_url('assets/' . $this->image) : 'https://via.placeholder.com/200x150.png?text='.__('asset::app.uploadAssetPicture');
    }
    //region Custom Functions

}

Modules/Asset/Entities/AssetType.php
<?php

namespace Modules\Asset\Entities;

use Illuminate\Database\Eloquent\Model;
use Modules\Asset\Observers\AssetObserver;

class AssetType extends Model
{
    //region Properties

    protected $table = 'asset_types';


    protected $hidden = [
        'created_at',
        'updated_at',
    ];

    protected $guarded = [
        'id',
        'created_at',
        'updated_at',
    ];


    protected $dates = [
        'created_at',
        'updated_at'
    ];

    //endregion

    //region Boot

    public static function boot()
    {
        parent::boot();
    }

    //endregion


    public function history()
    {
        return $this->hasMany(AssetHistory::class);
    }

    //endregion

    //region Custom Functions

}

Modules/Asset/Http/Controllers/AssetController.php
<?php

namespace Modules\Asset\Http\Controllers;

use App\Helper\Files;
use App\Helper\Reply;
use App\Http\Controllers\Member\MemberBaseController;
use App\User;
use Carbon\Carbon as Carbon;
use Illuminate\Http\Response;
use Modules\Asset\Datatables\AssetsDataTable;
use Modules\Asset\Entities\Asset;
use Modules\Asset\Entities\AssetHistory;
use Modules\Asset\Entities\AssetType;
use Modules\Asset\Http\Requests\LendRequest;
use Modules\Asset\Http\Requests\ReturnRequest;
use Modules\Asset\Http\Requests\StoreRequest;
use Modules\Asset\Http\Requests\UpdateRequest;

class AssetController extends MemberBaseController
{
    public function __construct()
    {
        parent::__construct();
        $this->pageTitle = __('asset::app.menu.asset');
        $this->pageIcon = 'icon-desktop';
    }

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index(AssetsDataTable $dataTable)
    {
        $this->assetType = AssetType::all();
        $this->employees = User::allEmployees();
        $this->totalAssets = Asset::count();
        $this->status = ['lent', 'available', 'non-functional'];
        return $dataTable->render('asset::asset.index', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        $this->assets = new Asset();
        $this->assetType = AssetType::all();
        return view('asset::asset.create', $this->data);
    }

    public function store(StoreRequest $request)
    {
        $asset = new Asset();
        $this->storeUpdate($asset, $request);

        return Reply::redirect(route('admin.assets.index'), 'asset::app.storeSuccess');
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function edit($id)
    {
        $this->asset = Asset::find($id);
        $this->assetType = AssetType::all();
        return view('asset::asset.edit', $this->data);
    }


    public function update(UpdateRequest $request, $id)
    {
        $asset = Asset::find($id);
        $this->storeUpdate($asset, $request);

        return Reply::redirect(route('admin.assets.index'), 'asset::app.updateSuccess');
    }

    private function storeUpdate($asset, $request)
    {
        $asset->name = $request->name;
        $asset->serial_number = $request->serial_number;
        $asset->asset_type_id = $request->asset_type_id;

        if($request->has('description')) {
            $asset->description = $request->description;
        }

        if($asset->status != 'lent') {
            $asset->status = $request->has('status') ? 'non-functional': 'available';
        }

        if ($request->hasFile('image')) {

            Files::deleteFile($asset->image, 'avatar');
            $asset->image = Files::upload($request->image, 'assets');
        }

        $asset->save();
    }

    public function show($id)
    {
        $this->asset = Asset::with(['history' => function($query) {
            return $query->orderBy('id', 'desc');
        }, 'asset_type'])->findOrFail($id);
        $view = view('asset::asset.show', $this->data)->render();
        return Reply::dataOnly(['status' => 'success', 'view' => $view]);
    }

    public function destroy($id)
    {
        Asset::destroy($id);
        return Reply::success(__('asset::app.deleteSuccess'));
    }
}

Modules/Asset/Resources/views/asset/create.blade.php
@extends('layouts.app')

@section('page-title')
    <div class="row bg-title">
        <!-- .page title -->
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title"><i class="{{ $pageIcon }}"></i> {{ $pageTitle }}</h4>
        </div>
        <!-- /.page title -->
        <!-- .breadcrumb -->
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <ol class="breadcrumb">
                <li><a href="{{ route('admin.dashboard') }}">@lang('app.menu.home')</a></li>
                <li><a href="{{ route('admin.assets.index') }}">{{ $pageTitle }}</a></li>
                <li class="active">@lang('app.addNew')</li>
            </ol>
        </div>
        <!-- /.breadcrumb -->
    </div>
@endsection

@push('head-script')
<link rel="stylesheet" href="{{ asset('plugins/bower_components/bootstrap-datepicker/bootstrap-datepicker.min.css') }}">
<link rel="stylesheet" href="{{ asset('plugins/bower_components/summernote/dist/summernote.css') }}">
<link rel="stylesheet" href="{{ asset('plugins/bower_components/bootstrap-select/bootstrap-select.min.css') }}">
<link rel="stylesheet" href="{{ asset('plugins/bower_components/custom-select/custom-select.css') }}">
<link rel="stylesheet" href="{{ asset('plugins/bower_components/multiselect/css/multi-select.css') }}">
    <style>
        .panel-black .panel-heading a:hover, .panel-inverse .panel-heading a:hover {
            color: #000 !important;
        }
        .panel-black .panel-heading a, .panel-inverse .panel-heading a {
            color: #000 !important;
        }
    </style>
@endpush

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-inverse">
                <div class="panel-heading"> @lang('asset::app.createTitle')</div>
                <div class="panel-wrapper collapse in" aria-expanded="true">
                    <div class="panel-body">
                        {!! Form::open(['id'=>'createAsset','class'=>'ajax-form','method'=>'POST','autocomplete'=>'off']) !!}
                            <div class="form-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label required">@lang('asset::app.assetName')</label>
                                            <input type="text" id="name" name="name" value="" class="form-control" >
                                        </div>
                                    </div>
                                    <!--/span-->
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label required">@lang('asset::app.assetType')
                                                <a href="javascript:;"
                                                   id="createAssetType"
                                                   class="btn btn-xs btn-outline btn-success">
                                                    <i class="fa fa-plus"></i> @lang('asset::app.addAssetType')
                                                </a></label>
                                            <select class="select2 form-control" name="asset_type_id" id="asset_type_id" data-style="form-control">
                                                @foreach($assetType as $type)
                                                    <option value="{{ $type->id }}">{{ $type->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label required">@lang('asset::app.serialNumber')</label>
                                            <input type="text" id="serial_number" name="serial_number" value="" class="form-control" >
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label">@lang('asset::app.status')</label>
                                            <div class="checkbox checkbox-info">
                                                <input id="status" name="status" value="true"
                                                       type="checkbox">
                                                <label for="random_password">@lang('asset::app.nonFunctional')</label>
                                            </div>
                                        </div>
                                    </div>


                                </div>
                                <!--/row-->
                                <div class="row">
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label class="control-label">@lang('asset::app.description')</label>
                                            <textarea name="description" rows="4" id="description" class="form-control"></textarea>
                                        </div>
                                    </div>
                                    <!--/span-->
                                </div>
                                <!--/row-->
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>@lang('asset::app.assetPicture')</label>
                                        <div class="form-group">
                                            <div class="fileinput fileinput-new" data-provides="fileinput">
                                                <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                                    <img src="http://via.placeholder.com/200x150.png?text=@lang('asset::app.uploadAssetPicture')"
                                                         alt=""/>
                                                </div>
                                                <div class="fileinput-preview fileinput-exists thumbnail"
                                                     style="max-width: 200px; max-height: 150px;"></div>
                                                <div>
                                <span class="btn btn-info btn-file">
                                    <span class="fileinput-new"> @lang('app.selectImage') </span>
                                    <span class="fileinput-exists"> @lang('app.change') </span>
                                    <input type="file" id="image" name="image"> </span>
                                                    <a href="javascript:;" class="btn btn-danger fileinput-exists"
                                                       data-dismiss="fileinput"> @lang('app.remove') </a>
                                                </div>
                                            </div>
                                        </div>

                                    </div>

                                </div>

                            </div>
                            <div class="form-actions">
                                <button type="submit" id="save-form" class="btn btn-success"> <i class="fa fa-check"></i> @lang('app.save')</button>
                                <a href="{{ route('admin.assets.index') }}" class="btn btn-default">@lang('app.back')</a>
                            </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>    <!-- .row -->
    {{--Ajax Modal--}}
    <div class="modal fade bs-modal-md in" id="taskCategoryModal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-md" id="modal-data-application">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <span class="caption-subject font-red-sunglo bold uppercase" id="modelHeading"></span>
                </div>
                <div class="modal-body">
                    Loading...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn blue">Save changes</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->.
    </div>
    {{--Ajax Modal Ends--}}
@endsection

@push('footer-script')
<script src="{{ asset('plugins/bower_components/bootstrap-datepicker/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ asset('plugins/bower_components/custom-select/custom-select.min.js') }}"></script>
<script src="{{ asset('plugins/bower_components/bootstrap-select/bootstrap-select.min.js') }}"></script>
<script src="{{ asset('plugins/bower_components/multiselect/js/jquery.multi-select.js') }}"></script>
<script src="{{ asset('plugins/bower_components/summernote/dist/summernote.min.js') }}"></script>
<script>
    $(".date-picker").datepicker({
        todayHighlight: true,
        autoclose: true
    });

    $(".select2").select2({
        formatNoMatches: function () {
            return "{{ __('messages.noRecordFound') }}";
        }
    });

    $('.summernote').summernote({
        height: 200,                 // set editor height
        minHeight: null,             // set minimum height of editor
        maxHeight: null,             // set maximum height of editor
        focus: false,
        toolbar: [
            // [groupName, [list of button]]
            ['style', ['bold', 'italic', 'underline', 'clear']],
            ['font', ['strikethrough']],
            ['fontsize', ['fontsize']],
            ['para', ['ul', 'ol', 'paragraph']],
            ["view", ["fullscreen"]]
        ]
    });

    $('#save-form').click(function () {
        $.easyAjax({
            url: '{{route('admin.assets.store')}}',
            container: '#createAsset',
            type: "POST",
            redirect: true,
            file:true
            // data: $('#createAsset').serialize()
        })
    });
    $('#createAssetType').click(function() {
        var url = '{{ route('admin.asset-type.create')}}';
        $('#modelHeading').html("@lang('assets::app.assetType')");
        $.ajaxModal('#taskCategoryModal', url);
    })
</script>
@endpush

Modules/Asset/Resources/views/asset/index.blade.php
@extends('layouts.app')

@section('page-title')
    <div class="row bg-title">
        <!-- .page title -->
        <div class="col-lg-8 col-md-5 col-sm-6 col-xs-12">
            <h4 class="page-title"><i class="{{ $pageIcon }}"></i> {{ $pageTitle }}
                <span class="text-info b-l p-l-10 m-l-5">{{ $totalAssets }}</span> <span
                        class="font-12 text-muted m-l-5"> @lang('asset::app.totalAssets')</span>
            </h4>
        </div>

        <!-- /.page title -->
        <!-- .breadcrumb -->
        <div class="col-lg-4 col-sm-6 col-md-7 col-xs-12 text-right">
            <a href="{{ route('admin.assets.create') }}"
               class="btn btn-outline btn-success btn-sm">@lang('asset::app.addNewAsset') <i class="fa fa-plus"
                                                                                                  aria-hidden="true"></i></a>
            <ol class="breadcrumb">
                <li><a href="{{ route('admin.dashboard') }}">@lang('app.menu.home')</a></li>
                <li class="active">{{ $pageTitle }}</li>
            </ol>
        </div>
        <!-- /.breadcrumb -->
    </div>
@endsection

@push('head-script')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css">
    <link rel="stylesheet" href="//cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.min.css">
    <link rel="stylesheet" href="//cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.min.css">
    <link rel="stylesheet" href="{{ asset('plugins/bower_components/bootstrap-select/bootstrap-select.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/bower_components/custom-select/custom-select.css') }}">
    <link rel="stylesheet"
          href="{{ asset('plugins/bower_components/bootstrap-datepicker/bootstrap-datepicker.min.css') }}">

    <style>

        .dashboard-stats .white-box .list-inline {
            margin-bottom: 0;
        }

        .dashboard-stats .white-box {
            padding: 10px;
        }

        .dashboard-stats .white-box .box-title {
            font-size: 13px;
            text-transform: capitalize;
            font-weight: 300;
        }
        #assets-table_wrapper .dt-buttons{
            display: none !important;
        }

    </style>
@endpush

@section('content')
    <div class="row">

        <div class="col-md-12">
            <div class="white-box">

                @section('filter-section')
                    <div class="row" id="ticket-filters">

                        <form action="" id="filter-form">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <h5>@lang('asset::app.assetType')</h5>
                                    <select class="select2 form-control" name="asset_type_id" id="asset_type_id" data-style="form-control">
                                        <option value="all">@lang('modules.client.all')</option>
                                        @foreach($assetType as $type)
                                            <option value="{{ $type->id }}">{{ $type->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <h5>@lang('asset::app.employees')</h5>
                                    <select class="select2 form-control" name="user_id" id="user_id" data-style="form-control">
                                        <option value="all">@lang('modules.client.all')</option>
                                        @foreach($employees as $employee)
                                            <option value="{{ $employee->id }}">{{ ucwords($employee->name) }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <h5>@lang('asset::app.status')</h5>
                                    <select class="select2 form-control" name="status" id="status" data-style="form-control">
                                        <option value="all">@lang('modules.client.all')</option>
                                        @foreach($status as $type)
                                            <option value="{{ $type }}">{{ ucwords($type) }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group p-t-10">
                                    <label class="control-label col-xs-12">&nbsp;</label>
                                    <button type="button" id="apply-filters" class="btn btn-success btn-sm col-md-6"><i
                                                class="fa fa-check"></i> @lang('app.apply')</button>
                                    <button type="button" id="reset-filters"
                                            class="btn btn-inverse col-md-5 btn-sm col-md-offset-1"><i
                                                class="fa fa-refresh"></i> @lang('app.reset')</button>
                                </div>
                            </div>
                        </form>
                    </div>
                @endsection

                <div class="table-responsive">
                    {!! $dataTable->table(['class' => 'table table-bordered table-hover toggle-circle default footable-loaded footable']) !!}
                </div>
            </div>
        </div>
    </div>
    <!-- .row -->
    {{--Ajax Modal--}}
    <div class="modal fade bs-modal-md in" id="assetModal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-md" id="modal-data-application">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <span class="caption-subject font-red-sunglo bold uppercase" id="modelHeading"></span>
                </div>
                <div class="modal-body">
                    Loading...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn blue">Save changes</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->.
    </div>
    {{--Ajax Modal Ends--}}
@endsection

@push('footer-script')
    <script src="{{ asset('plugins/bower_components/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.1.1/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.1.1/js/responsive.bootstrap.min.js"></script>
    <script src="{{ asset('plugins/bower_components/custom-select/custom-select.min.js') }}"></script>
    <script src="{{ asset('plugins/bower_components/bootstrap-select/bootstrap-select.min.js') }}"></script>
    <script src="{{ asset('plugins/bower_components/bootstrap-datepicker/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ asset('plugins/bower_components/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
    <script src="https://cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.min.js"></script>
    <script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

    {!! $dataTable->scripts() !!}
    <script>
        $(".select2").select2();

        jQuery('#date-range').datepicker({
            toggleActive: true,
            format: '{{ $global->date_picker_format }}',
            language: '{{ $global->locale }}',
            autoclose: true
        });
        var table;
        $(function () {
            $('body').on('click', '.sa-params', function () {
                var id = $(this).data('user-id');
                swal({
                    title: "Are you sure?",
                    text: "You will not be able to recover the deleted assets!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Yes, delete it!",
                    cancelButtonText: "No, cancel please!",
                    closeOnConfirm: true,
                    closeOnCancel: true
                }, function (isConfirm) {
                    if (isConfirm) {

                        var url = "{{ route('admin.assets.destroy',':id') }}";
                        url = url.replace(':id', id);

                        var token = "{{ csrf_token() }}";

                        $.easyAjax({
                            type: 'POST',
                            url: url,
                            data: {'_token': token, '_method': 'DELETE'},
                            success: function (response) {
                                if (response.status == "success") {
                                    $.easyBlockUI('#assets-table');
                                    window.LaravelDataTables["assets-table"].draw();
                                    $.easyUnblockUI('#assets-table');
                                }
                            }
                        });
                    }
                });
            });

        });

        $('.toggle-filter').click(function () {
            $('#ticket-filters').toggle('slide');
        })

        $('#apply-filters').click(function () {
            $('#assets-table').on('preXhr.dt', function (e, settings, data) {
                var asset_type = $('#asset_type_id').val();
                var user_id = $('#user_id').val();
                var status = $('#status').val();
                data['asset_type'] = asset_type;
                data['user_id'] = user_id;
                data['status'] = status;


            });

            $.easyBlockUI('#assets-table');
            window.LaravelDataTables["assets-table"].draw();
            $.easyUnblockUI('#assets-table');

        });

        $('#reset-filters').click(function () {
            $('#filter-form')[0].reset();
            $('#status').val('all');
            $('.select2').val('all');
            $('#filter-form').find('select').select2();

            $.easyBlockUI('#assets-table');
            window.LaravelDataTables["assets-table"].draw();
            $.easyUnblockUI('#assets-table');
        })

        $('#assets-table').on('click', '.asset-name', function () {
            $(".right-sidebar").slideDown(50).addClass("shw-rside");

            var id = $(this).data('asset-id');
            var url = "{{ route('admin.assets.show',':id') }}";
            url = url.replace(':id', id);

            $.easyAjax({
                type: 'GET',
                url: url,
                success: function (response) {
                    if (response.status == "success") {
                        $('#right-sidebar-content').html(response.view);
                    }
                }
            });
        })
        function lend(id) {
            var url = '{{ route('admin.history.create', ':id')}}';
            url = url.replace(':id', id);
            $('#modelHeading').html("@lang('asset::app.lend')");
            $.ajaxModal('#assetModal', url);
        }

        function returnAsset(history_id, asset_id) {
            var url = '{{ route('admin.assets.return', [':asset', ':history'])}}';
            url = url.replace(':asset', asset_id);
            url = url.replace(':history', history_id);
            console.log(url, 'hello from return');
            $('#modelHeading').html("@lang('asset::app.return')");
            $.ajaxModal('#assetModal', url);
        }

    </script>
@endpush